
export const ApiUrlConstants = {
  LOGIN: "/users/login",
  CREATE_EMPLOYEE: "/createEmployee",
  GET_ALL_EMPLOYEE: "/employeeGetAll",
  UPDATE_PASSWORD: "/empPasswordUpdate/",
  GET_ALL_CAFE: "/cafe/",
  VISITOR: "/visitor/",
  VISITOR_PAGE: "/visitor",
  POS_Staff_Service: "/possystem-staff-service/",
  VISITOR_UPDATE: "/visitor/visitorId=",
  TRAINING: "/training/",
  TRAINING_PAGE: "/training",
  NEW_TRAINING: "/training/trainingId=",
  TRAINING_DETAIL: "/trainingUser/",
  COURSE_REGISTRATION: "/courseRegisteration/",
  FILE_UPLOAD: "/uploadcourseRegisteration/", 
  LEAVE: "/leave/",
  GET_LEAVE_LIST: "/getUserLeave/",
  INVENTORY: "/inventory/",
  FOOD_CATEGORY: "/foodcategory/",
  PRINT_CATEGORY: "/printCategory/",
  GET_FOOD_CATEGORY: "/getfoodcategory/",
  GET_PRINT_CATEGORY: "/getprintCategory/",
  GET_FOOD_USAGE: "/getFoodUseage/",
  GET_PRINT_USAGE: "/getPrintUseage/",
  GET_SYS_USAGE: "/getSystemUseage/",
  POS: "/possystem/",
  LOGOFF: "/logoff/",
  RESTART: "/restartPc/",
  SEND_MESSAGE: "/SendMessage/",
  REVENUE: "/getRevenueByDate/",
  REVENUE_MONTH: "/getRevenueMonth/",
  INCOME_MONTH: "/getIncomeMonth",
  EXPENSE_MONTH: "/getExpenseMonth",
  INCOME: "/getIncomeByDate/",
  EXPENSE: "/getExpenseByDate/",
  DELETE_VISITOR: "/updateVisitorStatus/",
  DELETE_TRAINING: "/updateTrainingStatus/",
  GET_MEMBER: "/getMember/",
  GET_ALL_VISITOR: "/getAllVisitorReport/",
  GET_TRAINING_REPORT: "/getTrainingReport/",
  GET_USER_REPORT: '/getAllUserReport/',
  GET_POS_REPORT: "/getAllPOSReport/",
  GET_INCOME_REPORT: "/getAllIncomeReport",
  FORGOT_PASSWORD: "/forgetPassword",
  EMP_PASSWORD_UPDATE: "/empPasswordUpdate/",
  USER: "/users/",
  Update_EMPLOYEE: "/empUpdate/",
  UPLOAD: "/upload/",
  POS_SYSTEM_USER: "/possystemUser/",
  INVENTORY_ID: "/inventoryId?",
  VISITOR_UPLOAD: "/uploadVisitor/",
  TOTAL_HOURS: "/getTotalHours/",
  LOCATION_USER: "/locationUsers/",
  RECENT_ACTIVITY: "/getRecentActive/",
  BILL_GENERATE: "/billGeneration",
  BILL_CREATE: "/billCreate",
  CONTROL_BOT: "/home/controlbot/",
  VISITOR_GET: "/",
  TRAINING_TYPE_GET: "/trainingCategory/",
  TRAINING_TYPE_CREATE: "/trainingCategory",
  TRAINING_TYPE_UPDATE: "/trainingCategory/",
  TRAINING_TYPE_DELETE: "/trainingCategory/",

  GENDER_TYPE_GET: "/gender/",
  GENDER_TYPE_CREATE: "/gender",
  GENDER_TYPE_UPDATE: "/gender/",
  GENDER_TYPE_DELETE: "/gender/",

  NATIONALITY_TYPE_GET: "/nationality/",
  NATIONALITY_TYPE_CREATE: "/nationality",
  NATIONALITY_TYPE_UPDATE: "/nationality/",
  NATIONALITY_TYPE_DELETE: "/nationality/delete",

  INCOME_TYPE_GET: "/incomelevel/",
  INCOME_TYPE_CREATE: "/incomelevel",
  INCOME_TYPE_UPDATE: "/incomelevel/",
  INCOME_TYPE_DELETE: "/incomelevel/",

  MARITAL_TYPE_GET: "/maritalstatus/",
  MARITAL_TYPE_CREATE: "/maritalstatus",
  MARITAL_TYPE_UPDATE: "/maritalstatus/",
  MARITAL_TYPE_DELETE: "/maritalstatus/",

  OCCUPATION_GET: "/occupation/",
  OCCUPATION_CREATE: "/occupation",
  OCCUPATION_UPDATE: "/occupation/",
  OCCUPATION_DELETE: "/occupation/delete",

  TRAINING_ATTENDENCE: "/attendance",
  GET_ACTIVE_MEMBER_REPORT: "/report-activeMember",
  GET_ACTIVE_BY_GENDER: "/report-activeMemberbyGender",
  GET_ACTIVE_BY_BUMI: "/report-activeMemberbyBumi",
  GET_ACTIVE_BY_AGE: "/report-activeMemberbyage",
  GET_ACTIVE_BY_OCCUPATION: "/report-occupation",
  GET_BY_CLOCK_IN_CLOCK_OUT: "/captureclocktime",
  GET_BY_TRAINING_COURSE: "/report-trainingCourse",
  GET_BY_TRAINING_ATTENDANCE: "/report-trainingAttendance",
  GET_BY_CAFE_USAGE: "/report-cafeUsage",
  GET_BY_ACTIVE_CAFE_USAGE: "/report-activecafeUsage",
  GET_EXPENSE: "/report-income-expense-summary",
  GET_INCOME_DET: "/report-incomeexpenseDetail",
  GET_CLOCK_DET: "/report-clockinout",

  STATES_LIST: "/getstatelistBycountry/",
  COUNTRIES_LIST: "/country/",
  MEMBER_CODE: "/autogenerate/",

  EXPENSE_CREATE: "/expense",
  EXPENSE_GET: "/expense/",
  EXPENSE_UPDATE: "/expense/",
  EXPENSE_DELETE: "/expense/",

  PURCHASE_CREATE: "/purchase/",
  PURCHASE_GET: "/purchase/",
  PURCHASE_UPDATE: "/purchase/",
  PURCHASE_DELETE: "/purchase/",

  GET_NON_MEMBER_SET: "/billGeneration/",
  GET_MEMBER_SET: "/billGeneration/",

  UPDATE_MEMBER: "/billGeneration/",
  UPDATE_NON_MEMBER: "/billGeneration/",

  GST_UPDATE: "/taxsettings/",
  GST_GET: "/taxsettings/",

  MEMBER_DETAILS: "/membershipRegistration",

  GET_MEMBERSHIP: "/membershipRegistration/",

  GET_REGISTERED: "/getMemberList/",
  GET_RENEWAL: "/",

  // CHANGE_PC: "/inventorySystemstatusUpdate/",
  CHANGE_PC: "/changepc/",

  TOP_UP: "/topup/",

  CLOCK_TIME: "/captureclocktime/",
  TARGET_INV: "/targetGroup/",
  LEAVE_INV: "/leavetype/",
  CHECK_NRIC: "/membershipbyNricNo/",
  TAX_SETTINGS: "/taxsettings",

  SEND_MSG: '/controlbot',
  RESTART_PC: '/controlbot',
  LOCK_PC: '/controlbot',
  PING_PC : '/controlbot',
  SHUTDOWN_PC : '/controlbot',

}
