/* Anvesh */


export const ApiUrlConstants = {
  LOGIN: "/users/login",
  CREATE_EMPLOYEE: "/createEmployee/",
  UPDATE_PASSWORD: "/empPasswordUpdate/",
  GET_ALL_EMPLOYEE: "/employeeGetAll/",
  USER: "/users/",
  GET_ALL_CAFE: "/cafe/",
  Update_EMPLOYEE: "/empUpdate/",
  EMP_UPDATE_STATUS: "/empUpdateStatus/",
  VISITOR: "/visitor/",
  VISITOR_PAGE: "/visitor",
  VISITOR_UPDATE: "/visitor/visitorId=",
  TRAINING: "/training/",
  TRAINING_PAGE: "/training",
  NEW_TRAINING: "/training/trainingId=",
  TRAINING_DETAIL: "/trainingUser/",
  COURSE_REGISTRATION: "/courseRegisteration/",
  LEAVE: "/leave/",
  GET_LEAVE_LIST: "/getUserLeave/",
  INVENTORY: "/inventory/",
  FOOD_CATEGORY: "/foodcategory/",
  PRINT_CATEGORY: "/printCategory/",
  GET_FOOD_CATEGORY: "/getfoodcategory/",
  GET_PRINT_CATEGORY: "/getprintCategory/",
  GET_FOOD_USAGE: "/getFoodUseage/",
  GET_PRINT_USAGE: "/getPrintUseage/",
  GET_SYS_USAGE: "/getSystemUseage/",
  POS: "/possystem/",
  LOGOFF: "/logoff/",
  RESTART: "/restartPc/",
  SEND_MESSAGE: "/SendMessage/",
  REVENUE: "/getRevenueByDate/",
  REVENUE_MONTH: "/getRevenueMonth/",
  INCOME_MONTH: "/getIncomeMonth",
  EXPENSE_MONTH: "/getExpenseMonth",
  INCOME: "/getIncomeByDate/",
  EXPENSE: "/getExpenseByDate/",
  DELETE_VISITOR: "/updateVisitorStatus/",
  DELETE_TRAINING: "/updateTrainingStatus/",
  GET_MEMBER: "/getMember/",
  GET_ALL_VISITOR: "/getAllVisitorReport/",
  GET_TRAINING_REPORT: "/getTrainingReport/",
  GET_USER_REPORT: '/getAllUserReport/',
  GET_POS_REPORT: "/getAllPOSReport/",
  GET_INCOME_REPORT: "/getAllIncomeReport",
  UPLOAD: "/upload/",
  FORGOT_PASSWORD: "/forgetPassword",
  GET_LOCATION: "/cafe",
  GET_ALL_ROLES: "/getRoles",
  GET_ALL_REPORTS: "/getReports",
  CREATE_ROLE: "/roles",
  GET_ROLE_BY_ID: "/users/rolePermissions/",
  UPDATE_PERMISSION_BY_ROLE: "/users/permisiion",
  RESET_PASSWORD: "/users/resetPassword/",


  TRAINING_ATTENDENCE: "/attendance",
  GET_ACTIVE_MEMBER_REPORT: "/report-activeMember",
  GET_ACTIVE_BY_GENDER: "/report-activeMemberbyGender",
  GET_ACTIVE_BY_BUMI: "/report-activeMemberbyBumi",
  GET_ACTIVE_BY_AGE: "/report-activeMemberbyage",
  GET_ACTIVE_BY_OCCUPATION: "/report-activeMemberbyOccupation",
  GET_BY_TRAINING_COURSE: "/report-trainingCourse",
  GET_BY_TRAINING_ATTENDANCE: "/report-trainingAttendance",
  GET_BY_CAFE_USAGE: "/report-cafeUsage",
  GET_BY_ACTIVE_CAFE_USAGE: "/report-activecafeUsage",
  GET_EXPENSE: "/report-incomeexpensesummary",

}
